import Head from 'next/head'

import Header from '../../components/Header';


export default function PageAdm() {
  return (

    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
      <Header />
              <div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
              
              <span class="fs-4">Sidebar</span>
            </a>

            <ul class="nav nav-pills flex-column mb-auto">
              <li class="nav-item">
                <a href="#" class="nav-link active" aria-current="page">
                  
                  Home
                </a>
              </li>
              <li>
                <a href="#" class="nav-link link-dark">
                  
                  Dashboard
                </a>
              </li>
              <li>
                <a href="#" class="nav-link link-dark">
                  
                  Orders
                </a>
              </li>
              <li>
                <a href="#" class="nav-link link-dark">
                  
                  Products
                </a>
              </li>
              <li>
                <a href="#" class="nav-link link-dark">
                  
                  Customers
                </a>
              </li>
            </ul>

            <div class="dropdown">
              <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                
                <strong>mdo</strong>
              </a>
              <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                <li><a class="dropdown-item" href="#">New project...</a></li>
                <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><hr class="dropdown-divider"/></li>
                <li><a class="dropdown-item" href="#">Sign out</a></li>
              </ul>
            </div>
          </div>

      </main>
    </div>
  )
}
