import Head from 'next/head'
import Link from 'next/link';

import Header from '../../components/Header';

export default function PageAdm() {
  return (

    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className='container p-5'>
        <div className='card'>
          <div className='row p-4 centered'>
            <div className='col-3 p-3 bot'>
              <Link href="/admin/listarusuario"><a className="">Consulta Usuarios</a></Link>
            </div>
            <div className='col-3 p-3 bot'>
              <Link href="/admin/listaremp"><a className="">Consulta Empresas</a></Link>
            </div>
            <div className='col-3 p-3 bot'>
              <Link href="/admin/listarcorretor"><a className="">Consulta Corretores</a></Link>
            </div>
            <div className='col-3 p-3 bot'>
              <Link href="/admin/listarcorretor"><a className="">Consulta Corretores</a></Link>
            </div>
          </div>
        </div>

      </div>
    </div>
  )
}
