import Head from 'next/head'
import Link from 'next/link';

import Header from '../../components/Header';



export default function PageAdm() {
  return (

    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className='container p-5'>
        <div className='card'>
          <div className='row p-4'>
            <div className='col-4 p-3'>
              <Link href="/admin/listar"><a className="btn btn-secondary w-100 mb-2">Listar Usuarios</a></Link>
            </div>
            <div className='col-4 p-3'>
              <Link href="/admin/listaremp"><a className="btn btn-secondary w-100 mb-2">Listar Empresas</a></Link>
            </div>
            <div className='col-4 p-3'>
              <Link href="/admin/listarcorretor"><a className="btn btn-secondary w-100 mb-2">Listar Corretores</a></Link>
            </div>
          </div>
        </div>

      </div>
    </div>
  )
}
