import Head from 'next/head'
import Link from 'next/link';

import conectarDB from '../../lib/dbConnect'
import Imobiliaria from '../../models/Imobiliaria'
import Header from "../../components/Header"

export default function Listar({ imobiliarias }) {
  return (
    <div>
      <Head>
        <title>Lista de Contatos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
      </div>
      <main className="container">
        <h1>Imobiliarias!</h1>
        <div className='centered col-md-6'>
          <Link href="/admin/imobiliaria/new"><a className="btn btn-secondary w-100 mb-2">Adicionar Imobiliaria</a></Link>
        </div>

        <div className="d-flex p-2">
          <div className="d-flex">
            {
              imobiliarias.map(({ _id, namefantasia }) => (
                <div className="" key={_id}>
                  <div className="justify-content-center m-3">
                    <svg className="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777" /><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
                    <h2 className="fw-normal text-center">{namefantasia}</h2>
                    <div className="text-center">
                      <Link href={`/admin/imobiliaria/${_id}`}>
                        <a className="btn btn-success btn-sm">+Info</a>
                      </Link>
                    </div>

                  </div>
                </div>
              ))
            }



          </div>
        </div>


      </main>
    </div>
  )
}

export async function getServerSideProps() {
  try {
    await conectarDB()

    const res = await Imobiliaria.find({});

    const imobiliarias = res.map(doc => {
      const imobiliaria = doc.toObject();
      imobiliaria._id = `${imobiliaria._id}`;
      return imobiliaria;
    })

    return { props: { imobiliarias} };
  } catch (error) {
    console.log(error);
  }
}