import Head from 'next/head'
import Link from 'next/link';

import conectarDB from '../lib/dbConnect'
import Movie from '../models/Movie'
import Header from '../components/Header';


export default function Home({movies}) {
  return (

    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
      <Header />
       
      </main>
    </div>
  )
}

export async function getServerSideProps(){
  try {
      await conectarDB()
      
      const res = await Movie.find({});

      const movies = res.map(doc =>{
          const movie = doc.toObject();
          movie._id = `${movie._id}`;
          return movie;
      })
      
      return {props: {movies}};
  } catch (error) {
    console.log(error);
  }
}