import Head from 'next/head'
import Link from 'next/link';


import Header from '../components/Header';


export default function Home({ }) {
//  https://dev.to/rafacdomin/autenticacao-no-react-com-context-api-e-hooks-4bia
//react context api login example
  return (

    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className='container teste'>
        <div className='container'>
          <h1 >SEJA BEM VINDO!</h1>
        </div>
      </main>


    </div>
  )
}
