import Head from 'next/head'
import Link from 'next/link';
import Form from "../../../components/Postagem"

import Header from '../../../components/Header';

export default function MeusDados() {
  const formData = {
    namejuridico: "",
    namefantasia: "",
    cnpj: "",
    cidade: "",
    email: "",
    telefone: "",
  };
  return (

    <div>
      <Head>
        <title>Meus Dados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className='container'>
        <div className='d-flex flex-column centro'>
          <div className='p-2'>
            <h1>Minha Conta</h1>
          </div>
          <div className='p-2 flex-row'>

            <div className='d-flex'>
              <div className='d-flex flex-column'>
                <Link href='/meusdados/editarperfil/'><a className="p-2 botoes">Editar Perfil</a></Link>
                <Link href='/meusdados/minhaspostagens/'><a className="p-2 botoes">Minhas Postagens</a></Link>
                <Link href='/meusdados/saldo/'><a className="p-2 botoes">Meus Saldo</a></Link>
              </div>
              <div className='info'>
                <div className='opcoes'>
                  <div className='centered col-md-6'>
                    <div>
                    <Form formData={formData} />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
