import Head from 'next/head'
import Link from 'next/link';


import Header from '../../../components/Header';


export default function Home({ }) {
    //  https://dev.to/rafacdomin/autenticacao-no-react-com-context-api-e-hooks-4bia
    //react context api login example
    return (

        <div>
            <Head>
                <title>Index</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <main className='container meio'>
                <div className='d-flex p-4 justify-content-between'>
                    <Link href={`/login/register/new`}>
                        <a className='alogin'>
                            <div className='d-flex p-2 btlogin centered'>Corretor</div>
                        </a>
                    </Link>
                    <Link href={`/login/registrar/new2`}>
                        <a className='alogin'>
                            <div className='d-flex p-2 btlogin centered'>Pessoa Fisica</div>
                        </a>
                    </Link>
                </div>
            </main>


        </div>
    )
}
